site_name: 小白程序员成长日记
repo_url: https://github.com/mqaaa
site_description: 在忙碌的生活中，梦想应更加耀眼。
site_author: 豚豚
copyright: <a href="http://www.miitbeian.gov.cn/">晋ICP备18013421号</a>
# copyright: [晋ICP备18013421号](http://www.miitbeian.gov.cn/)
# theme: bootstrap


nav:
- Home: 'index.md'
- Vue:
  - '日常贴士': './vue/experience.md'
  - 'Styling your docs': 'styling-your-docs.md'
- Echanrt/d3:
  - 'Writing your docs': 'writing-your-docs.md'
  - 'Styling your docs': 'styling-your-docs.md'
- Python:
  - 'Jupyer': './python/jupyter.md'
  - 'Python': './python/Python.md'
  - 'License': 'license.md'
  - 'Release Notes': 'release-notes.md'
- Go:
  - 'Writing your docs': 'writing-your-docs.md'
  - 'Styling your docs': 'styling-your-docs.md'
- 面试:
  - '逻辑&创新思维': './interview/logical.md'
- 心得:
  - '前端篇': './noticpoint/javascript.md'

